const menu = [
    {
        id: 1,
        title: 'Camden Display Cabinet',
        category: 'Living',
        price: 999.00,
        img: './images/item-1.jpg',
        desc: `Our Camden range pieces are handmade by skilled craftsmen from sustainable white oak using time tested construction methods. `,
    },
    {
        id: 2,
        title: 'Cascais 7 Drawer Lowboy',
        category: 'Bedroom',
        price: 699.00,
        img: './images/item-2.jpg',
        desc: `Welcome to our vibrant Cascais collection. These funky pieces have a deep blue painted body with lightly chamfered edges that let a little pop of natural timber to outline the main body and drawers. This stylish body is contrasted nicely by the oiled oak top and antiqued handles. `,
    },
    {
        id: 3,
        title: 'Felixstowe King Bed Frame',
        category: 'Bedroom',
        price: 699.00,
        img: './images/item-3.jpg',
        desc: `These good looking bed frames keep all the features of the rest of the range, while adding some great accenting on the head and foot boards. The frames come disassembled for easy transport and can be put up in around 10 minutes.`,
    },
    {
        id: 4,
        title: 'Danube Granite Oak Kitchen Island',
        category: 'Kitchen',
        price: 1499.00,
        img: './images/item-4.jpg',
        desc: `SWhether you're short on bench space or want a smooth stone surface for prep work, you can't go wrong with one of these rock solid kitchen islands. `,
    },
    {
        id: 5,
        title: 'Firm Pocket Spring Mattress',
        category: 'Bedroom',
        price: 699.00,
        img: './images/item-5.jpg',
        desc: `If you've had your mattress for 8 years or more then it really is time to look at replacing it. Springs sag, foam gets thin and unsupportive, and it can negatively impact your sleep.`,
    },
    {
        id: 6,
        title: 'Double Bed & Mattress',
        category: 'Bedroom',
        price: 699.00,
        img: './images/item-6.jpg',
        desc: `From out Trent range of affordable solid timber furniture these pieces offer fantastic value for money. Their timeless design, beautiful rimu toned finish, and rock solid construction make these a wonderful addition to your bedroom.`,
    },
    {
        id: 7,
        title: 'Vancouver King Slat Bed',
        category: 'Bedroom',
        price: 699.00,
        img: './images/item-7.jpg',
        desc: `Our Vancouver collection is made from New Zealand pine with a light lime washed finish. Each piece has a modern, minimalist aesthetic with clean lines. `,
    },
    {
        id: 8,
        title: 'Versailles Large Oak Bookcase',
        category: 'Living',
        price: 1299.00,
        img: './images/item-8.jpg',
        desc: `This large and spacious bookcase has 9 individual sections that could shelve a ton of books or display your favourite photos or ornaments. At the base of the unit is 3 spacious drawers to store away anything that isn't quite display worthy. `,
    },
    {
        id: 9,
        title: 'Vienna Oak Butchers Block',
        category: 'Kitchen',
        price: 799.00,
        img: './images/item-9.jpg',
        desc: `Our Vienna range are beautiful pieces of oak furniture that feature clean lines, a golden polished finish, stylish tapered legs, and are finished off with heavy gauge rustic brass handles.`,
    },
];
export default menu;